site_name: Documentation segmentation semantique
site_author: Mathieu Klimczak
dev_addr: "127.0.0.1:8001"
theme:
  name: material
  logo: images/logo_blanc.svg
  icon:
    repo: fontawesome/brands/gitlab
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Basculer en mode sombre
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Basculer en mode clair

# extra_css:
#   - stylesheets/extra.css

plugins:
  - search:
      lang: fr
  - mkdocstrings:
      watch:
        - src
        - tests
        - configs
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
            - sys.path.append("tests")
          rendering:
            show_source: true

nav:
  - Acceuil: index.md
  - Hydra configuration: hydra_config/hydra.md
  - Various configuration:
    - Docker config: misc_config/docker.md
    - Makefile : misc_config/make.md
    - Requirements: misc_config/requirements.md
  - Datasets creation:
    - Dataset configuration: datasets/config.md
    - Masks creation: datasets/utils_segmentation.md
    - Train-Test-Val datasets creation: datasets/make_dataset.md
    - Datasets pipelines:
      - Classic pipeline: datasets/classic.md
      - CutMix pipeline: datasets/cutmix.md
  - Semantic segmentation:
    - Architecture descrption: models/description.md
    - Common layers: models/common_layers.md
    - Backbones:
      - MobileNetv2: models/backbone/mobilenetv2.md
      - GhostNet: models/backbone/ghostnet.md
      - VoVNet: models/backbone/vovnet.md
      - ResNet50: models/backbone/resnet50.md
      - ResNet50v2: models/backbone/resnet50v2.md
      - ResNet101: models/backbone/resnet101.md
      - ResNet101v2: models/backbone/resnet101v2.md
    - Segmentation heads:
      - KSAC: models/heads/ksac.md
      - FPN: models/heads/fpn.md
      - OCNet: models/heads/ocnet.md
      - JPU: models/heads/jpu.md
  - Training loop: train.md
  - Loss: loss/focal_loss.md
  - Metrics : metrics/mean_iou.md
  # - Tests unitaires:
  #   - tensorize: test_tensorize.md
  #   - prepare_dataset: test_make_dataset.md
  #   - utils: test_utils.md



markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
  - def_list
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.betterem:
      smart_enable: all
  # config pour latex
  - pymdownx.arithmatex:
      generic: true

# config pour latex
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
