_target_: model.backbone.convmlp.get_backbone
img_shape: ${datasets.params.img_shape}
channels: 64
n_conv_blocks: 3
num_blocks: [3,6,3]
units: [128,128,256,512]
mlp_ratios: [3,3,3]
backbone_name: ConvMLP-M
