_target_: models.backbone.convmlp.get_backbone
img_shape: ${datasets.params.img_shape}
channels: 96
n_conv_blocks: 3
num_blocks: [4,8,3]
units: [192,192,384,768]
mlp_ratios: [3,3,3]
backbone_name: ConvMLP-L
