_target_: model.backbone.convmlp.get_backbone
img_shape: ${datasets.params.img_shape}
channels: 64
n_conv_blocks: 2
num_blocks: [2,4,2]
units: [128,128,256,512]
mlp_ratios: [2,2,2]
backbone_name: ConvMLP-S
