_target_: models.backbone.mobilevit.get_backbone
img_shape: ${datasets.params.img_shape}
expansion_rate: [2, 2]
filters: [16, 16, 24, 24, 24, 48, 48, 64, 64, 80, 80, 320]
emb_dim: [64, 80, 96]
repetitions: [2, 4, 3]
num_heads: 2
backbone_name: MobileViT-XXS
