_target_: models.backbone.mobilevit.get_backbone
img_shape: ${datasets.params.img_shape}
expansion_rate: [4, 2]
filters: [16, 16, 64, 64, 64, 96, 96, 128, 128, 160, 160, 640]
emb_dim: [144, 192, 240]
repetitions: [2, 4, 3]
num_heads: 2
backbone_name: MobileViT-S
