_target_: model.tiramisu.get_segmentation_model
filters: 16
nb_blocks: 5
nb_layers: [4, 5, 7, 10, 12, 15, 12, 10, 7, 5, 4]
nb_filters: 48
n_classes: ${datas.n_classes}
img_shape: ${datas.img_shape}

# 103 layers (FC-DenseNet103) with a growth rate of 16.
