defaults:
  - backbone: mobilevit_xs
  - segmentation_model: ocnet
  - losses: focal_loss
  - optimizer: cg_adam
  - lr_decay: cosine_decay_restart
  - metrics: mean_iou
  - datasets: datasets
  - pipeline: classic
  - training: custom_training

# or classification
task: segmentation

start:
  from_saved_model: false
  saved_model_dir: null


lrd:
  activate: true

prepare:
  split: 0.15
  seed: 42

monitoring:
  experiment_name: SegmentationProject
  run_name: ${backbone.backbone_name}_${segmentation_model.name}_${now:%Y-%m-%d_%H-%M-%S}

log:
  timestamp: ${now:%Y-%m-%d_%H-%M-%S}
hydra:
  run:
    dir: hydra/${now:%Y-%m-%d_%H-%M-%S} #_${hydra.job.override_dirname}
#   sweep:
#     dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
#     subdir: ${hydra.job.override_dirname}

# mlflow se charge déjà de faire le tracking des hyperparamètres, inutile de l'avoir en double.
# décommenter la section au dessus pour avoir un tracking de chaque run par hydra.
# hydra:
#   output_subdir: null
